### ISSUE TITLE
...options  ^ ParseError: Unexpected token

### ISSUE THREAD

**Issue by sliktrik** [juampi92/adonis-mongoose-model#10]
Trying to run 'adonis make:mongoose Foo' as per the guide and get the following error.

/node_modules/adonis-mongoose-model/providers/MongooseProvider.js:50
        ...options
        ^
ParseError: Unexpected token

**Comment by CherryDT** [comment]
Looks like you are running an old version of node.js (older than v6).

However, I think you will have more problems in that case because Adonis v4 (which is required for this module) itself already requires modern node.js... So, can it be that you have old Adonis too?

**Comment by sliktrik** [comment]
T'was my node version, previously had 7.4.0, upgraded to 9.8.4 and it works perfectly.

Thank you
