### ISSUE TITLE
Cannot store ObjectID data type to session store - Serializer should return only trivial types for findById/findByUid

### ISSUE THREAD

**Issue by CherryDT** [juampi92/adonis-mongoose-model#11]
When attempting authorization using a session, we get the error "Cannot store ObjectID data type to session store". The reason for this is that the user model returned by the serializer contains non-trivial types, in particular `ObjectID` (at least for the `_id` field).

Note that even `toObject`/`toJSON` would not fix this (`toJSON` just returns something that will be properly converted to JSON even if it's a class instance, but the AdonisJS session store actually checks the types and rejects those objects).

My current solution is to run this on startup, because I wanted to avoid forking your module and keeping it up to date afterwards:

```
/*
  Goal of this file is to prevent the MongooseSerializer from returning "live" Mongoose models which
  then fail to be stored in a session because they contain non-trivial types such as ObjectID.
*/

module.exports = () => {
  const MongooseSerializer = use('adonis-mongoose-model/src/Serializers/MongooseSerializer')

  function wrapWithSanitizer (klass, method) {
    const oldMethod = klass.prototype[method]

    klass.prototype[method] = async function (...args) {
      const result = await oldMethod.call(this, ...args)
      return result ? JSON.parse(JSON.stringify(result)) : result
    }
  }

  wrapWithSanitizer(MongooseSerializer, 'findById')
  wrapWithSanitizer(MongooseSerializer, 'findByUid')

  // Not sure if this is needed also for 'listTokens'?
}
```

It would be nice if this could be handled in the serializer itself already.

**Comment by juampi92** [comment]
Hi!
It's a bummer that the Session Store does not casts the ObjectID.
I did this workaround, let me know what you think:

https://github.com/juampi92/adonis-mongoose-model/commit/c4acfa8474e78df4ea3e32e15fe530a8a3a71a86

Basically I made a virtual accessor '__id' that returns the _id casted into a String, and made the Serializer use the __id if the _id was returned as primaryKey.

**Comment by CherryDT** [comment]
Hmm, I realize now, isn't this already done by default as `id`?

http://mongoosejs.com/docs/api.html#document_Document-id

**Comment by juampi92** [comment]
Oh my....
Rolling back.... 😅

**Comment by juampi92** [comment]
2.2.0 is live on [npm](https://www.npmjs.com/package/adonis-mongoose-model)

**Comment by CherryDT** [comment]
Thank you!
