### ISSUE TITLE
buildSchema does not return schema unless it already exists

### ISSUE THREAD

**Issue by CherryDT** [juampi92/adonis-mongoose-model#12]
It looks like buildSchema is supposed to return the schema and create it if it doesn't exist.

However, at the moment, it seems like buildSchema returns the schema only if it already exists, otherwise it creates the schema but returns undefined.

Therefore, adding methods/virtuals/etc. to the schema is unnecessarily complex because it involves calling `buildSchema` at least twice (or accessing the "private" property `_schema`):

```
// we need:

this.buildSchema();
const schema = this.buildSchema();
schema.virtual('something').get(.......);

// or:

this.buildSchema();
this._schema.virtual('something').get(.......);

// instead of simply:

const schema = this.buildSchema();
schema.virtual('something').get(.......);
```

**Comment by juampi92** [comment]
What do you think of this?
https://github.com/juampi92/adonis-mongoose-model/commit/9daecc00ea83a8b7563c3ed2adf09640bcf89db2

**Comment by CherryDT** [comment]
1) I apparently missed the fact that I can access this._schema in boot already.
2) The changes look great, thank you!
