### ISSUE TITLE
Hidden fields in Model

### ISSUE THREAD

**Issue by bryannbarbosa** [juampi92/adonis-mongoose-model#15]
Is there a way to leave some hidden fields at the time of consultation?
For example, I would like to hide the password field, but I would not want to do this every time in every query.

In the Lucid documentation, there is the hidden () method, which returns the fields to be hidden, is there anything similar that I can use with mongoose?

**Comment by juampi92** [comment]
Maybe this is what you want: https://www.npmjs.com/package/mongoose-hidden

You'd install this plugin using something like this

````javascript
'use strict'

const BaseModel = use('Model')
const mongooseHidden = require('mongoose-hidden')()

/**
 * @class Foo
 */
class Foo extends BaseModel {
  static boot ({ schema }) {
    schema.plugin(mongooseHidden);
  }
  /**
   * Foo's schema
   */
  static get schema () {
    return {
      name: String,
      password: { type: String, hide: true },
      email: String
    }
  }
}

module.exports = Foo.buildModel('Foo')

````
