### ISSUE TITLE
Remove Model alias to be compatible with lucidjs

### ISSUE THREAD

**Issue by mcordoba** [juampi92/adonis-mongoose-model#17]
https://github.com/juampi92/adonis-mongoose-model/blob/4a8c3693687730641d99fcf2394880f0a49e00ef/providers/MongooseProvider.js#L64

I think this should be removed and added to the documentation to do it manually as you do with the Mongoose alias. I have installed the provider and now I can't use lucidjs Model.

Thank you for this useful provider :)

**Comment by juampi92** [comment]
Solved this issue on release 3.0.0

https://github.com/juampi92/adonis-mongoose-model/releases/tag/3.0.0
