### ISSUE TITLE
Adding virtual fields to schema

### ISSUE THREAD

**Issue by mcordoba** [juampi92/adonis-mongoose-model#19]
Is it possible to add virtual fields using this package?

schema only returns the fields but I want to add a virtual field and I don't know where to add the function to handle it.

Thank you

**Comment by juampi92** [comment]
Sure you do. Check out the [example model](https://github.com/juampi92/adonis-mongoose-model/blob/master/instructions.md#creating-models) (or the default created by the command) to see [how to access the raw schema](https://github.com/juampi92/adonis-mongoose-model/blob/master/instructions.md#extra-accessing-the-raw-schema) before it's built into the model.
