### ISSUE TITLE
Are you still planning to implement the expiration of token?

### ISSUE THREAD

**Issue by jericopulvera** [juampi92/adonis-mongoose-model#28]
```
  jwt: {
    serializer: 'mongoose',
    scheme: 'jwt',
    model: 'App/Models/User',
    token: 'App/Models/Token',
    uid: 'email',
    password: 'password',
    expiry: '30d', // Not yet implemented
    options: {
      secret: Config.get('app.appKey')
    }
  },
```

**Comment by jericopulvera** [comment]
Would like to know the default for the current expiration.

**Comment by juampi92** [comment]
You'll have to configure it here, when extending the Token Model.

https://github.com/juampi92/adonis-mongoose-model/blob/master/src/Model/TokenMongoose.js#L42

Yes, it should be configured on the config instead, but I forgot about it. I'll let you know when it's out, but right now I'm busy. You could do a PR yourself if you want.
