### ISSUE TITLE
Factory.js does not work.

### ISSUE THREAD

**Issue by jericopulvera** [juampi92/adonis-mongoose-model#34]
What do you think of Factory integration.

**Comment by juampi92** [comment]
Meaning?

But PRs are welcome anyway man, feel free to show me your idea

**Comment by jericopulvera** [comment]
The idea is to make the [factories](https://adonisjs.com/docs/4.1/seeds-and-factories) work with mongoose .

I'll definitely submit a pr when I got the time. :+1:

**Comment by juampi92** [comment]
True. It seems really nice. Great, looking forward for the PR then :)
