### ISSUE TITLE
"TypeError: user.primaryKeyValue is not a function at MongooseSerializer.deleteTokens

### ISSUE THREAD

**Issue by jericopulvera** [juampi92/adonis-mongoose-model#35]
https://adonisjs.com/docs/4.1/authentication#_jwt

I'm trying revokeTokensForUser but it gives me errors

"TypeError: user.primaryKeyValue is not a function at MongooseSerializer.deleteTokens
```
  async logout ({ request, response, auth }) {
    const user = await this.User.find(auth.user._id)

    await auth.authenticator('jwt').revokeTokensForUser(user)

    return response.apiSuccess(user)
  }
```

**Comment by juampi92** [comment]
https://forum.adonisjs.com/t/revoke-jwt-token-for-user/2006

**Comment by ianmustafa** [comment]
What about refresh token? I have same problem for `generateForRefreshToken()`

```js
  async refresh ({ request, response, auth }) {
    const newToken = await auth.newRefreshToken()
      .generateForRefreshToken(request.input('refreshToken'));

    return response.json(newToken);
  };
```

in this case, the refresh token is indeed saved in `Token` collection
