### ISSUE TITLE
Is possible to use mongoose-autopopulate?

### ISSUE THREAD

**Issue by jonjts** [juampi92/adonis-mongoose-model#48]
HI there

Is possible to use [mongoose-autopopulate](https://github.com/mongodb-js/mongoose-autopopulate) to auto populate the relationships? If not, exist other way to auto populate relationships?

**Comment by juampi92** [comment]
You can define your schema by just redefining the 

```js
static get schema () {
    return {

    }
  }
```

https://github.com/juampi92/adonis-mongoose-model/blob/master/instructions.md#defining-schema
