### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by unairubio** [juampi92/adonis-mongoose-model#51]
Mongo is giving out this error `{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoError: password must be a string]`

This is due to the config in the docs being incorrect, the correct one would look like:

```
  mongodb: {
    client: 'mongodb',
    connectionString: Env.get('DB_CONNECTION_STRING', ''),
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      port: Env.get('DB_PORT', 27017),
      user: Env.get('DB_USER', 'admin'),
      pass: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis'),
          options: {
            // All options can be found at http://mongoosejs.com/docs/connections.html
            useNewUrlParser: true // stops throwing warning
          },
    }
  }
```
We need to polish this module for a production environment so I will just fork it and create a pull request with all the things we find when we are done.

**Comment by unairubio** [comment]
Resolved in my branch, will reintegrate soon enough.

**Comment by juampi92** [comment]
Hey!
I'm not familiar with the `useNewUrlParser`, but yes, PRs are more than welcome! Thanks a lot :)
