### ISSUE TITLE
Access ObjectId from model

### ISSUE THREAD

**Issue by unairubio** [juampi92/adonis-mongoose-model#52]
Maybe there is something I am missing here, but how do we access the `ObjectId` type from a model?

It seems inelegant to have to import mongoose on every model such as: `const { ObjectId } = use('mongoose').Schema.Types`.

If it's not there (can't seem to see it in the code) we should probably find a way to make this property available from `BaseModel`.

Thanks!

**Comment by juampi92** [comment]
Why would BaseModel be the one to provide a schema type?
I think that doing as you mentioned

```js
const { ObjectId } = use('mongoose').Schema.Types.
```

is more than fine, since mongoose is the one that provides the schema types.

**Comment by unairubio** [comment]
@juampi92 Mainly because it decouples even more the module from mongoose, so that the user doesn't have to interact with it directly. 

Second, it's a common use case, so it reduces the overhead of having to include it on almost every model.
