### ISSUE TITLE
hook preSave not working on use updateOne

### ISSUE THREAD

**Issue by vitorleonel** [juampi92/adonis-mongoose-model#55]
I have an endpoint for update user password, but when use Model.updateOne method, hooks is not called.

See my mode boot:

```javascript
static boot({ schema }) {
    this.addHook('preSave', 'UserHook.hashPassword')
    this.addHook('preUpdate', 'UserHook.hashPassword')
}
```

See my hook:

```javascript
'use strict'

const Hash = use('Hash')

const UserHook = (exports = module.exports = {})

UserHook.hashPassword = async (user) => {
  user.password = await Hash.make(user.password)
}
```

Can you help me?

**Comment by vitorleonel** [comment]
I try use `preUpdate` but not have success :(

**Comment by juampi92** [comment]
Hooks only work for updates on the instance, not when triggering remote updates. You'll have to first load the User, then change the password, and then trigger a save.

**Comment by juampi92** [comment]
Try checking the "hooks" documentation

https://mongoosejs.com/docs/middleware.html#pre
Maybe you should be looking for `pre('updateOne')` which should be `preUpdateOne`
