### ISSUE TITLE
adonis make command in infinite execution

### ISSUE THREAD

**Issue by vitorleonel** [juampi92/adonis-mongoose-model#56]
After install your package (incredible per signal), i have problem when using `adonis make...` because the execution not finish, i wait per long 10 minutes and not have result, but the file is created :(

My hypothesis is that mongodb is also running when using commands.

Your see this problem on yours projects?

**Comment by vitorleonel** [comment]
Additional information:

After start infinite execution, my terminal is blocked, CTRL+C not resolve for cancel operation, the solution is close terminal.

**Comment by juampi92** [comment]
Yes, the Service Provider will load mongoose. Can't you just define your mongodb connection? It should work if the connection is correct.
