### ISSUE TITLE
Moongose Options

### ISSUE THREAD

**Issue by JoshDev1205** [juampi92/adonis-mongoose-model#7]
Hello,

I love your module its very helpful.

But i want to have some example about the object in the model.

for example i want to pass some options like usePushEach

How can i do that ??

Thks for your help

**Comment by juampi92** [comment]
Hi.
I'm not sure I get what you are asking, but I'll tell you both configuration options available.

First, on connection. Using the options mentioned [here](http://mongoosejs.com/docs/connections.html), you can customize them on your config/database.js, under the `options` object.

[Here's the source for that](https://github.com/juampi92/adonis-mongoose-model/blob/master/providers/MongooseProvider.js#L50)

Then if you'd like to modify your schema creation, you can, but it's a bit trickier. If you can wait maybe today (need more testing), I'm about to push a new version with improved schema options API.

http://mongoosejs.com/docs/guide.html#options 

You can do it by personalizing the `static boot ()` method, accessing the schema using `this._schema` and adding there the options like
`this._schema.set(option, value)`

Or you can, before calling `buildModel` , use `Model.buildSchema( { ...options } )` and then the model will use that options when calling buildModel.

-----
I couldn't find your option `usePushEach` on the mongoose documentation, so if you explain to me how that options was used on mongoose I might help you, or add that on the next version.
